# Generated by Django 3.1.2 on 2020-11-23 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('montototal', models.FloatField()),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasenna', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('stock', models.FloatField()),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mediopago',
            fields=[
                ('id_mediopago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('estado', models.FloatField()),
            ],
            options={
                'db_table': 'mediopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menucategoria',
            fields=[
                ('id_menucategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'menucategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id_menuitem', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('estado', models.FloatField()),
            ],
            options={
                'db_table': 'menuitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('numeromesa', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.FloatField()),
                ('sector', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.FloatField()),
            ],
            options={
                'db_table': 'mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechareserva', models.DateField()),
                ('horareserva', models.CharField(max_length=25)),
                ('numeromesa', models.FloatField()),
                ('estadoreserva', models.FloatField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roltrabajador',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionrol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roltrabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudinsumo',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fechasolicitud', models.DateField()),
                ('estado', models.FloatField()),
                ('comentario', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'solicitudinsumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasenna', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsumoSolicitud',
            fields=[
                ('id_solicitud', models.OneToOneField(db_column='id_solicitud', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.solicitudinsumo')),
                ('cantidadsolicitada', models.FloatField()),
            ],
            options={
                'db_table': 'insumo_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menuiteminsumo',
            fields=[
                ('id_menuitem', models.OneToOneField(db_column='id_menuitem', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.menuitem')),
                ('cantidad', models.FloatField()),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'menuiteminsumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidomenuitem',
            fields=[
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.pedido')),
                ('cantidad', models.FloatField()),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pedidomenuitem',
                'managed': False,
            },
        ),
    ]
